package neuralnetwork;

import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultCaret;

public class NeuralNetworkUI extends javax.swing.JFrame {
    
    private Thread th;
    private DefaultCaret caret;
    private Object[][] tabla;
    private int[] entrada;
    private DefaultTableModel dtm;
    private int tFil, tCol;
    
    //Instancia de clase que contiene las matrices para representar los dígitos
    Digitos digitos = new Digitos();
    
    //Instancia de clase que contiene el algoritmo de la red neuronal
    BackProp back = new BackProp();
    
    //Cadena que muestra la salida del programa
    private static String salida = "";

    /**
     * Creates new form NeuralNetworkUI
     */
    public NeuralNetworkUI() {
        
        initComponents();
        caret = (DefaultCaret)jTextAreaOutput.getCaret();
        caret.setUpdatePolicy(DefaultCaret.OUT_BOTTOM);        
        entrada = new int[42];
    }
    
    public static void updateOutput(String s) {
        salida += s;
        jTextAreaOutput.setText(salida);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTraining = new javax.swing.JButton();
        jButtonView = new javax.swing.JButton();
        jTextFieldAlpha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldError = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIterations = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOutput = new javax.swing.JTextArea();
        jButtonStopTraining = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldShow = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonClasif = new javax.swing.JButton();
        Check54 = new javax.swing.JCheckBox();
        Check55 = new javax.swing.JCheckBox();
        Check50 = new javax.swing.JCheckBox();
        Check51 = new javax.swing.JCheckBox();
        Check52 = new javax.swing.JCheckBox();
        Check53 = new javax.swing.JCheckBox();
        Check44 = new javax.swing.JCheckBox();
        Check45 = new javax.swing.JCheckBox();
        Check40 = new javax.swing.JCheckBox();
        Check41 = new javax.swing.JCheckBox();
        Check42 = new javax.swing.JCheckBox();
        Check43 = new javax.swing.JCheckBox();
        Check34 = new javax.swing.JCheckBox();
        Check35 = new javax.swing.JCheckBox();
        Check30 = new javax.swing.JCheckBox();
        Check31 = new javax.swing.JCheckBox();
        Check32 = new javax.swing.JCheckBox();
        Check33 = new javax.swing.JCheckBox();
        Check24 = new javax.swing.JCheckBox();
        Check25 = new javax.swing.JCheckBox();
        Check20 = new javax.swing.JCheckBox();
        Check21 = new javax.swing.JCheckBox();
        Check22 = new javax.swing.JCheckBox();
        Check23 = new javax.swing.JCheckBox();
        Check14 = new javax.swing.JCheckBox();
        Check15 = new javax.swing.JCheckBox();
        Check10 = new javax.swing.JCheckBox();
        Check11 = new javax.swing.JCheckBox();
        Check12 = new javax.swing.JCheckBox();
        Check13 = new javax.swing.JCheckBox();
        Check04 = new javax.swing.JCheckBox();
        Check05 = new javax.swing.JCheckBox();
        Check00 = new javax.swing.JCheckBox();
        Check01 = new javax.swing.JCheckBox();
        Check02 = new javax.swing.JCheckBox();
        Check03 = new javax.swing.JCheckBox();
        Check64 = new javax.swing.JCheckBox();
        Check65 = new javax.swing.JCheckBox();
        Check60 = new javax.swing.JCheckBox();
        Check61 = new javax.swing.JCheckBox();
        Check62 = new javax.swing.JCheckBox();
        Check63 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        Digito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Redes Neuronales Dígitos");
        setMinimumSize(new java.awt.Dimension(100, 100));

        jButtonTraining.setText("Entrenar");
        jButtonTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrainingActionPerformed(evt);
            }
        });

        jButtonView.setText("Ver datos iniciales");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });

        jTextFieldAlpha.setText("0.6");
        jTextFieldAlpha.setMinimumSize(new java.awt.Dimension(40, 20));
        jTextFieldAlpha.setPreferredSize(new java.awt.Dimension(40, 20));

        jLabel1.setText("Alpha");

        jLabel2.setText("Error");

        jTextFieldError.setText("0.4");
        jTextFieldError.setMinimumSize(new java.awt.Dimension(40, 20));
        jTextFieldError.setPreferredSize(new java.awt.Dimension(40, 20));

        jLabel3.setText("Iteraciones");

        jTextFieldIterations.setText("100000");
        jTextFieldIterations.setMinimumSize(new java.awt.Dimension(80, 20));
        jTextFieldIterations.setPreferredSize(new java.awt.Dimension(80, 20));

        jTextAreaOutput.setEditable(false);
        jTextAreaOutput.setColumns(20);
        jTextAreaOutput.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jTextAreaOutput.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOutput);

        jButtonStopTraining.setText("Detener");
        jButtonStopTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopTrainingActionPerformed(evt);
            }
        });

        jLabel4.setText("Mostrar datos cada");

        jTextFieldShow.setText("100");
        jTextFieldShow.setMinimumSize(new java.awt.Dimension(60, 20));
        jTextFieldShow.setPreferredSize(new java.awt.Dimension(60, 20));
        jTextFieldShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldShowActionPerformed(evt);
            }
        });

        jLabel5.setText("iteraciones");

        jButtonClasif.setText("Clasificar");
        jButtonClasif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClasifActionPerformed(evt);
            }
        });

        Check54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check54ActionPerformed(evt);
            }
        });

        Check55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check55ActionPerformed(evt);
            }
        });

        Check50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check50ActionPerformed(evt);
            }
        });

        Check51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check51ActionPerformed(evt);
            }
        });

        Check52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check52ActionPerformed(evt);
            }
        });

        Check53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check53ActionPerformed(evt);
            }
        });

        Check44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check44ActionPerformed(evt);
            }
        });

        Check45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check45ActionPerformed(evt);
            }
        });

        Check40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check40ActionPerformed(evt);
            }
        });

        Check41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check41ActionPerformed(evt);
            }
        });

        Check42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check42ActionPerformed(evt);
            }
        });

        Check43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check43ActionPerformed(evt);
            }
        });

        Check34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check34ActionPerformed(evt);
            }
        });

        Check35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check35ActionPerformed(evt);
            }
        });

        Check30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check30ActionPerformed(evt);
            }
        });

        Check31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check31ActionPerformed(evt);
            }
        });

        Check32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check32ActionPerformed(evt);
            }
        });

        Check33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check33ActionPerformed(evt);
            }
        });

        Check24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check24ActionPerformed(evt);
            }
        });

        Check25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check25ActionPerformed(evt);
            }
        });

        Check20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check20ActionPerformed(evt);
            }
        });

        Check21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check21ActionPerformed(evt);
            }
        });

        Check22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check22ActionPerformed(evt);
            }
        });

        Check23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check23ActionPerformed(evt);
            }
        });

        Check14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check14ActionPerformed(evt);
            }
        });

        Check15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check15ActionPerformed(evt);
            }
        });

        Check10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check10ActionPerformed(evt);
            }
        });

        Check11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check11ActionPerformed(evt);
            }
        });

        Check12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check12ActionPerformed(evt);
            }
        });

        Check13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check13ActionPerformed(evt);
            }
        });

        Check04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check04ActionPerformed(evt);
            }
        });

        Check05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check05ActionPerformed(evt);
            }
        });

        Check00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check00ActionPerformed(evt);
            }
        });

        Check01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check01ActionPerformed(evt);
            }
        });

        Check02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check02ActionPerformed(evt);
            }
        });

        Check03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check03ActionPerformed(evt);
            }
        });

        Check64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check64ActionPerformed(evt);
            }
        });

        Check65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check65ActionPerformed(evt);
            }
        });

        Check60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check60ActionPerformed(evt);
            }
        });

        Check61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check61ActionPerformed(evt);
            }
        });

        Check62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check62ActionPerformed(evt);
            }
        });

        Check63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check63ActionPerformed(evt);
            }
        });

        jLabel6.setText("El dígito es:");

        Digito.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Digito.setText("?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonTraining)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonStopTraining))
                                            .addComponent(jButtonView)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(14, 14, 14)))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Digito)
                                .addGap(55, 55, 55)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonClasif)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Check50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check51)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check53)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check54)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Check55))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Check40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Check45))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Check30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Check35))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Check20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Check25))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Check10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Check15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Check00)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check02)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check03)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check04)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Check05))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Check60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check61)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check62)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check63)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Check64)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Check65)))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Check00)
                            .addComponent(Check01)
                            .addComponent(Check02)
                            .addComponent(Check03)
                            .addComponent(Check04)
                            .addComponent(Check05))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Check10)
                            .addComponent(Check11)
                            .addComponent(Check12)
                            .addComponent(Check13)
                            .addComponent(Check14)
                            .addComponent(Check15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Check20)
                            .addComponent(Check21)
                            .addComponent(Check22)
                            .addComponent(Check23)
                            .addComponent(Check24)
                            .addComponent(Check25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Check30)
                            .addComponent(Check31)
                            .addComponent(Check32)
                            .addComponent(Check33)
                            .addComponent(Check34)
                            .addComponent(Check35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Check40)
                            .addComponent(Check41)
                            .addComponent(Check42)
                            .addComponent(Check43)
                            .addComponent(Check44)
                            .addComponent(Check45))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Check50)
                            .addComponent(Check51)
                            .addComponent(Check52)
                            .addComponent(Check53)
                            .addComponent(Check54)
                            .addComponent(Check55))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Check60)
                            .addComponent(Check61)
                            .addComponent(Check62)
                            .addComponent(Check63)
                            .addComponent(Check64)
                            .addComponent(Check65))
                        .addGap(18, 20, Short.MAX_VALUE)
                        .addComponent(jButtonClasif))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTraining)
                            .addComponent(jButtonStopTraining))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonView)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Digito)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrainingActionPerformed
        salida = "";
        updateOutput("Comienza algoritmo...\n\n");
        th = new Thread(() -> {
            back.setParams(
                    Double.parseDouble(jTextFieldAlpha.getText()),
                    Double.parseDouble(jTextFieldError.getText()),
                    Integer.parseInt(jTextFieldIterations.getText()),
                    Integer.parseInt(jTextFieldShow.getText())
            );
            back.getResult();
        });
        th.start();
    }//GEN-LAST:event_jButtonTrainingActionPerformed

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        back.getInitVars();
    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jButtonStopTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopTrainingActionPerformed
        back.stopIterations(false);
    }//GEN-LAST:event_jButtonStopTrainingActionPerformed

    private void jButtonClasifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClasifActionPerformed
        Digito.setText("?");
        
    }//GEN-LAST:event_jButtonClasifActionPerformed

    private void Check54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check54ActionPerformed
        // TODO add your handling code here:
        if(Check54.isSelected()){
            entrada[34]=1;
        }else
            entrada[34]=0;
    }//GEN-LAST:event_Check54ActionPerformed

    private void Check55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check55ActionPerformed
        // TODO add your handling code here:
        if(Check55.isSelected()){
            entrada[35]=1;
        }else
            entrada[35]=0;
    }//GEN-LAST:event_Check55ActionPerformed

    private void Check50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check50ActionPerformed
        // TODO add your handling code here:
        if(Check50.isSelected()){
            entrada[30]=1;
        }else
            entrada[30]=0;
    }//GEN-LAST:event_Check50ActionPerformed

    private void Check51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check51ActionPerformed
        // TODO add your handling code here:
        if(Check51.isSelected()){
            entrada[31]=1;
        }else
            entrada[31]=0;
    }//GEN-LAST:event_Check51ActionPerformed

    private void Check52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check52ActionPerformed
        // TODO add your handling code here:
        if(Check52.isSelected()){
            entrada[32]=1;
        }else
            entrada[32]=0;
    }//GEN-LAST:event_Check52ActionPerformed

    private void Check53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check53ActionPerformed
        // TODO add your handling code here:
        if(Check53.isSelected()){
            entrada[33]=1;
        }else
            entrada[33]=0;
    }//GEN-LAST:event_Check53ActionPerformed

    private void Check44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check44ActionPerformed
        // TODO add your handling code here:
        if(Check44.isSelected()){
            entrada[28]=1;
        }else
            entrada[28]=0;
    }//GEN-LAST:event_Check44ActionPerformed

    private void Check45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check45ActionPerformed
        // TODO add your handling code here:
        if(Check45.isSelected()){
            entrada[29]=1;
        }else
            entrada[29]=0;
    }//GEN-LAST:event_Check45ActionPerformed

    private void Check40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check40ActionPerformed
        // TODO add your handling code here:
        if(Check40.isSelected()){
            entrada[24]=1;
        }else
            entrada[24]=0;
    }//GEN-LAST:event_Check40ActionPerformed

    private void Check41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check41ActionPerformed
        // TODO add your handling code here:
        if(Check41.isSelected()){
            entrada[25]=1;
        }else
            entrada[25]=0;
    }//GEN-LAST:event_Check41ActionPerformed

    private void Check42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check42ActionPerformed
        // TODO add your handling code here:
        if(Check42.isSelected()){
            entrada[26]=1;
        }else
            entrada[26]=0;
    }//GEN-LAST:event_Check42ActionPerformed

    private void Check43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check43ActionPerformed
        // TODO add your handling code here:
        if(Check43.isSelected()){
            entrada[27]=1;
        }else
            entrada[27]=0;
    }//GEN-LAST:event_Check43ActionPerformed

    private void Check34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check34ActionPerformed
        // TODO add your handling code here:
        if(Check34.isSelected()){
            entrada[22]=1;
        }else
            entrada[22]=0;
    }//GEN-LAST:event_Check34ActionPerformed

    private void Check35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check35ActionPerformed
        // TODO add your handling code here:
        if(Check35.isSelected()){
            entrada[23]=1;
        }else
            entrada[23]=0;
    }//GEN-LAST:event_Check35ActionPerformed

    private void Check30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check30ActionPerformed
        // TODO add your handling code here:
        if(Check30.isSelected()){
            entrada[18]=1;
        }else
            entrada[18]=0;
    }//GEN-LAST:event_Check30ActionPerformed

    private void Check31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check31ActionPerformed
        // TODO add your handling code here:
        if(Check31.isSelected()){
            entrada[19]=1;
        }else
            entrada[19]=0;
    }//GEN-LAST:event_Check31ActionPerformed

    private void Check32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check32ActionPerformed
        // TODO add your handling code here:
        if(Check32.isSelected()){
            entrada[20]=1;
        }else
            entrada[20]=0;
    }//GEN-LAST:event_Check32ActionPerformed

    private void Check33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check33ActionPerformed
        // TODO add your handling code here:
        if(Check33.isSelected()){
            entrada[21]=1;
        }else
            entrada[21]=0;
    }//GEN-LAST:event_Check33ActionPerformed

    private void Check24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check24ActionPerformed
        // TODO add your handling code here:
        if(Check24.isSelected()){
            entrada[16]=1;
        }else
            entrada[16]=0;
    }//GEN-LAST:event_Check24ActionPerformed

    private void Check25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check25ActionPerformed
        // TODO add your handling code here:
        if(Check25.isSelected()){
            entrada[17]=1;
        }else
            entrada[17]=0;                    
    }//GEN-LAST:event_Check25ActionPerformed

    private void Check20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check20ActionPerformed
        // TODO add your handling code here:
        if(Check20.isSelected()){
            entrada[12]=1;
        }else
            entrada[12]=0;
    }//GEN-LAST:event_Check20ActionPerformed

    private void Check21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check21ActionPerformed
        // TODO add your handling code here:
        if(Check21.isSelected()){
            entrada[13]=1;
        }else
            entrada[13]=0;
    }//GEN-LAST:event_Check21ActionPerformed

    private void Check22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check22ActionPerformed
        // TODO add your handling code here:
        if(Check22.isSelected()){
            entrada[14]=1;
        }else
            entrada[14]=0;
    }//GEN-LAST:event_Check22ActionPerformed

    private void Check23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check23ActionPerformed
        // TODO add your handling code here:
        if(Check23.isSelected()){
            entrada[15]=1;
        }else
            entrada[15]=0;
    }//GEN-LAST:event_Check23ActionPerformed

    private void Check14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check14ActionPerformed
        // TODO add your handling code here:
        if(Check14.isSelected()){
            entrada[10]=1;
        }else
            entrada[10]=0;
    }//GEN-LAST:event_Check14ActionPerformed

    private void Check15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check15ActionPerformed
        // TODO add your handling code here:
        if(Check15.isSelected()){
            entrada[11]=1;
        }else
            entrada[11]=0;
    }//GEN-LAST:event_Check15ActionPerformed

    private void Check10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check10ActionPerformed
        // TODO add your handling code here:
        if(Check10.isSelected()){
            entrada[6]=1;
        }else
            entrada[6]=0;
    }//GEN-LAST:event_Check10ActionPerformed

    private void Check11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check11ActionPerformed
        // TODO add your handling code here:
        if(Check11.isSelected()){
            entrada[7]=1;
        }else
            entrada[7]=0;
    }//GEN-LAST:event_Check11ActionPerformed

    private void Check12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check12ActionPerformed
        // TODO add your handling code here:
        if(Check12.isSelected()){
            entrada[8]=1;
        }else
            entrada[8]=0;
    }//GEN-LAST:event_Check12ActionPerformed

    private void Check13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check13ActionPerformed
        // TODO add your handling code here:
        if(Check13.isSelected()){
            entrada[9]=1;
        }else
            entrada[9]=0;
    }//GEN-LAST:event_Check13ActionPerformed

    private void Check04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check04ActionPerformed
        // TODO add your handling code here:
        if(Check04.isSelected()){
            entrada[4]=1;
        }else
            entrada[4]=0;
    }//GEN-LAST:event_Check04ActionPerformed

    private void Check05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check05ActionPerformed
        // TODO add your handling code here:
        if(Check05.isSelected()){
            entrada[5]=1;
        }else
            entrada[5]=0;
    }//GEN-LAST:event_Check05ActionPerformed

    private void Check00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check00ActionPerformed
        // TODO add your handling code here:
        if(Check00.isSelected()){
            entrada[0]=1;
        }else
            entrada[0]=0;
    }//GEN-LAST:event_Check00ActionPerformed

    private void Check01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check01ActionPerformed
        // TODO add your handling code here:
        if(Check01.isSelected()){
            entrada[1]=1;
        }else
            entrada[1]=0;
    }//GEN-LAST:event_Check01ActionPerformed

    private void Check02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check02ActionPerformed
        // TODO add your handling code here:
        if(Check02.isSelected()){
            entrada[2]=1;
        }else
            entrada[2]=0;
    }//GEN-LAST:event_Check02ActionPerformed

    private void Check03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check03ActionPerformed
        // TODO add your handling code here:
        if(Check03.isSelected()){
            entrada[3]=1;
        }else
            entrada[3]=0;
    }//GEN-LAST:event_Check03ActionPerformed

    private void Check64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check64ActionPerformed
        // TODO add your handling code here:
        if(Check64.isSelected()){
            entrada[40]=1;
        }else
            entrada[40]=0;
    }//GEN-LAST:event_Check64ActionPerformed

    private void Check65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check65ActionPerformed
        // TODO add your handling code here:
        if(Check65.isSelected()){
            entrada[41]=1;
        }else
            entrada[41]=0;
    }//GEN-LAST:event_Check65ActionPerformed

    private void Check60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check60ActionPerformed
        // TODO add your handling code here:
        if(Check60.isSelected()){
            entrada[36]=1;
        }else
            entrada[36]=0;
    }//GEN-LAST:event_Check60ActionPerformed

    private void Check61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check61ActionPerformed
        // TODO add your handling code here:
        if(Check61.isSelected()){
            entrada[37]=1;
        }else
            entrada[37]=0;
    }//GEN-LAST:event_Check61ActionPerformed

    private void Check62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check62ActionPerformed
        // TODO add your handling code here:
        if(Check62.isSelected()){
            entrada[38]=1;
        }else
            entrada[38]=0;
    }//GEN-LAST:event_Check62ActionPerformed

    private void Check63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check63ActionPerformed
        // TODO add your handling code here:
        if(Check60.isSelected()){
            entrada[39]=1;
        }else
            entrada[39]=0;
    }//GEN-LAST:event_Check63ActionPerformed

    private void jTextFieldShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException
                | InstantiationException
                | IllegalAccessException
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NeuralNetworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NeuralNetworkUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Check00;
    private javax.swing.JCheckBox Check01;
    private javax.swing.JCheckBox Check02;
    private javax.swing.JCheckBox Check03;
    private javax.swing.JCheckBox Check04;
    private javax.swing.JCheckBox Check05;
    private javax.swing.JCheckBox Check10;
    private javax.swing.JCheckBox Check11;
    private javax.swing.JCheckBox Check12;
    private javax.swing.JCheckBox Check13;
    private javax.swing.JCheckBox Check14;
    private javax.swing.JCheckBox Check15;
    private javax.swing.JCheckBox Check20;
    private javax.swing.JCheckBox Check21;
    private javax.swing.JCheckBox Check22;
    private javax.swing.JCheckBox Check23;
    private javax.swing.JCheckBox Check24;
    private javax.swing.JCheckBox Check25;
    private javax.swing.JCheckBox Check30;
    private javax.swing.JCheckBox Check31;
    private javax.swing.JCheckBox Check32;
    private javax.swing.JCheckBox Check33;
    private javax.swing.JCheckBox Check34;
    private javax.swing.JCheckBox Check35;
    private javax.swing.JCheckBox Check40;
    private javax.swing.JCheckBox Check41;
    private javax.swing.JCheckBox Check42;
    private javax.swing.JCheckBox Check43;
    private javax.swing.JCheckBox Check44;
    private javax.swing.JCheckBox Check45;
    private javax.swing.JCheckBox Check50;
    private javax.swing.JCheckBox Check51;
    private javax.swing.JCheckBox Check52;
    private javax.swing.JCheckBox Check53;
    private javax.swing.JCheckBox Check54;
    private javax.swing.JCheckBox Check55;
    private javax.swing.JCheckBox Check60;
    private javax.swing.JCheckBox Check61;
    private javax.swing.JCheckBox Check62;
    private javax.swing.JCheckBox Check63;
    private javax.swing.JCheckBox Check64;
    private javax.swing.JCheckBox Check65;
    private javax.swing.JLabel Digito;
    private javax.swing.JButton jButtonClasif;
    private javax.swing.JButton jButtonStopTraining;
    private javax.swing.JButton jButtonTraining;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea jTextAreaOutput;
    private javax.swing.JTextField jTextFieldAlpha;
    private javax.swing.JTextField jTextFieldError;
    private javax.swing.JTextField jTextFieldIterations;
    private javax.swing.JTextField jTextFieldShow;
    // End of variables declaration//GEN-END:variables
}
